export const INSERT_T_SHAPE = 'INSERT_T_SHAPE'
export const INSERT_L_SHAPE = 'INSERT_L_SHAPE'
export const INSERT_THREE_BOX_LINE = 'INSERT_THREE_BOX_LINE'
export const INSERT_ONE_BLOCK = 'INSERT_ONE_BLOCK'
export const INSERT_TWO_BY_TWO_L = 'INSERT_TWO_BY_TWO_L'
export const INSERT_TWO_BOX_COLUMN = 'INSERT_TWO_BOX_COLUMN'
export const INSERT_TWO_BY_TWO_SQUARE = 'INSERT_TWO_BY_TWO_SQUARE'
export const INSERT_THREE_BY_THREE_SQUARE = 'INSERT_THREE_BY_THREE_SQUARE'
export const CHOOSE_THREE_RAND_SHAPES = 'CHOOSE_THREE_RAND_SHAPES'
export const REMOVE_FROM_SHAPE_LIST = 'REMOVE_FROM_SHAPE_LIST'

export const SET_SELECTED_POSITION = 'SET_SELECTED_POSITION'
export const CLEAR_SELECTION = 'CLEAR_SELECTION'

export const CHECK_FOR_COMPETIONS = 'CHECK_FOR_COMPETIONS'

export const CHECK_IF_SHAPE_FITS = 'CHECK_IF_SHAPE_FITS'

export const CHANGE_DRAG_POSITION = 'CHANGE_DRAG_POSITION'

export const RESTART_GAME = 'RESTART_GAME'
